config/routes.rb
Rails.application.routes.draw do

  #dynamic error pages
  #get 'errors/not_found'
  #get 'errors/internal_server_error'

  #match "/404", :to => "errors#not_found", :via => :all
  #match "/500", :to => "errors#internal_server_error", :via => :all

  #home page
  root 'application#home'

  #
  resources :application

  resources :worlds do
    resources :plots
    resources :characters
  end

  resources :plots
  resources :characters

  #personal index
  get '/my-worlds' => 'worlds#profile'

  #other profiles
  get '/:user_id' => 'application#profile'

  #view world with most plots 
  get 'worlds/most-plots' => 'worlds#show'

  #
  devise_for :users, controllers: {registrations: "registrations", 
    omniauth_callbacks: "callbacks"}

  devise_scope :user do 
      get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do 
    get 'logout', to: 'devise/sessions#destroy'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   # before_action :authenticate_user!
   # skip_before_action :authenticate_user!, :only => [:home]
    
    #helper_method :set_world, :set_character, :set_plot
   # helper_method :set_world, :set_character, :set_plot


    def home
    end 

    def profile
        @user = User.find_by_id(params[:user_id])
        @worlds = @user.worlds
      #  byebug
    end

  

    def set_world
        @world = World.find(params[:id])
    end

    def set_character
        @character = Character.find(params[:id])
    end

    def set_plot
        @plot = Plot.find(params[:id])
    end


end

app/helpers/application_helper.rb
module ApplicationHelper

    def set_world
        #(world)
        world = World.find(params[:id])
    end

    def set_character
        #(character)
        character = Character.find(params[:id])
    end

    def set_plot
        #(plot)
        plot = Plot.find(params[:id])
    end

end

app/views/application/_errors.html.erb
<% if !!flash[:errors] %>
<ul>
<% flash[:errors].each do |e| %>
  <li><%= e %></li>
  <% end %>
</ul>
<% end %>

app/views/application/home.html.erb
<h1>Welcome to Worlding!</h1>
<p>Here you can share your world and character ideas, 
as well as read up on others.</p>
<br>
<br>
    <h3>Want the world with the most plots?</h3>

    <%= link_to "Click here", worlds_most_plots_path %> to view the world with the most plots.
    
<br>
<br>
<br>
<h3>
   <a href="/my-worlds"> Your Worlds! </a>
</h3>
    
    

app/views/application/profile.html.erb
<h2>
Here are the worlds belonging to: <%= @user.name %>!
</h2>

<p>
Here is a list of all of their worlds:

</p>

<ul>
<% @worlds.each do |w| %>

    <li><%= link_to w.name, world_path(w) %> ||
   </li> 
   
<% end %>
</ul>